name: cod_hammer
description: "cod_hammer"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.17
  translator: ^1.0.3+1
  video_player: ^2.6.0
  fl_chart: ^0.70.2
  chewie: ^1.4.0
  http: ^1.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  pie_chart: ^5.4.0
  percent_indicator: ^4.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  # Ensure this is set to true
  fonts:
    - family: Cornerita
      fonts:
        - asset: assets/fonts/Cornerita-Regular.ttf
    - family: StalinistOne
      fonts:
        - asset: assets/fonts/StalinistOne-Regular.ttf
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow-Regular.ttf

  assets:
    - assets/avatar_1.png
    - assets/avatar_2.png
    - assets/avatar_actual.png
    - assets/avatar_passed.png
    - assets/Active_bet.png
    - assets/Active_calendar.png
    - assets/Active_person.png
    - assets/Active_quiz.png
    - assets/Bet.png
    - assets/Calendar.png
    - assets/Evtihiev.png
    - assets/Fight_robots.png
    - assets/Person.png
    - assets/Quiz.png
    - assets/Bet_.png
    - assets/Quiz_.png
    - assets/time_actual.png
    - assets/time_passed.png
    - assets/videos/sample_video.mp4
    - assets/au.jpg
    - assets/weber.png
    - assets/вебер_лабс.jpg
    - assets/auxilium_ai.jpeg
    - assets/screw.png
    - assets/quiz.svg